# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQ7OBpNnAYBtikUGqzFhV32z6Umjff8U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load the dataset
df = pd.read_csv('jobSalary.csv')


print("Dataset Shape:", df.shape)
print(df.head())

# Initial Inspection
print(df.info())
print(df.head())

# Set visualization style
sns.set_theme(style="whitegrid")

#Average Salary by Job Title
plt.figure(figsize=(12, 6))
df.groupby('job_title')['salary'].mean().sort_values().plot(kind='barh', color='skyblue')
plt.title('Average Salary by Job Title')
plt.xlabel('Average Salary ($)')
plt.show()

#Salary by Education Level (Boxplot)
plt.figure(figsize=(10, 5))
edu_order = ['High School', 'Diploma', 'Bachelor', 'Master', 'PhD']
sns.boxplot(data=df, x='education_level', y='salary', palette='Set2', order=edu_order)
plt.title('Salary Distribution by Education Level')
plt.show()

#Correlation Heatmap
plt.figure(figsize=(8, 6))
numeric_cols = ['experience_years', 'skills_count', 'certifications', 'salary']
corr = df[numeric_cols].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Numerical Feature Correlations')
plt.show()

# Select features for clustering
segment_data = df[['experience_years', 'skills_count', 'salary']]

# Standardize the features
scaler = StandardScaler()
scaled_features = scaler.fit_transform(segment_data)

# Apply K-Means
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Segment'] = kmeans.fit_predict(scaled_features)

# Visualize the resulting segments
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='experience_years', y='salary', hue='Segment', palette='viridis', alpha=0.5)
plt.title('Professional Segments: Experience vs. Salary')
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df_model = df.copy()
categorical_cols = ['job_title', 'education_level', 'industry', 'company_size', 'location', 'remote_work']

for col in categorical_cols:
    df_model[col] = le.fit_transform(df_model[col])


X = df_model.drop(columns=['salary', 'segment_label'], errors='ignore')
y = df_model['salary']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)



# 1. Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

print("\n--- Linear Regression Metrics ---")
print(f"MAE: {mean_absolute_error(y_test, y_pred_lr):.2f}")
print(f"R^2 Score: {r2_score(y_test, y_pred_lr):.4f}")

# 2. Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=50, random_state=100)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("\n--- Random Forest Metrics ---")
print(f"MAE: {mean_absolute_error(y_test, y_pred_rf):.2f}")
print(f"R^2 Score: {r2_score(y_test, y_pred_rf):.4f}")

import pandas as pd
import matplotlib.pyplot as plt


features = [
    'job_title', 'experience_years', 'education_level', 'skills_count',
    'industry', 'company_size', 'location', 'certifications'
]


plt.figure(figsize=(10, 6))


feat_importances = pd.Series(rf_model.feature_importances_, index=features)


feat_importances.sort_values().plot(kind='barh', color='teal')
plt.title('Most Important Factors Influencing Salary')
plt.xlabel('Importance Score')
plt.ylabel('Factors')
plt.tight_layout()
plt.show()

df.to_csv('job_salary_processed.csv', index=False)

print("Segmentation complete! Your clean CSV is ready for Power BI.")